#Specify language and versions
language: python
python:
    - "3.7"

cache: pip

# install dependencies (in this case i have given 1 though not needed)
install:
    - pip install -r requirements.txt
    - pip install codecov

# run tests
script:
    - export PYTHONPATH=$PYTHONPATH:$(pwd)
    - python UnitTests.py
    - coverage run UnitTests.py

after_success:
    - codecov
